### PR TITLE
[BUGFIX] Better detection of application models

### LINKED ISSUE #122: PG::UndefinedTable: ERROR:  relation "read_marks" does not exist
When I run:

    rails generate administrate:install

I get:

     postgresql_adapter.rb:596:in `async_exec': PG::UndefinedTable: ERROR:  relation "read_marks" does not exist (ActiveRecord::StatementInvalid)
    LINE 5:                WHERE a.attrelid = '"read_marks"'::regclass
                                              ^
    :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                         pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                    FROM pg_attribute a LEFT JOIN pg_attrdef d
                      ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                   WHERE a.attrelid = '"read_marks"'::regclass
                     AND a.attnum > 0 AND NOT a.attisdropped
                   ORDER BY a.attnum

### PR DESCRIPTION
**Pull request by graysonwright**
Closes #122.

## Problem:

Administrate assumes that all subclasses of `ActiveRecord::Base` are backed by database tables.

When a host application or gem defines a subclass of `ActiveRecord::Base` that doesn't have a corresponding database table, the installation generator sees an error:

```
postgresql_adapter.rb:596:in `async_exec': PG::UndefinedTable: ERROR:  relation "read_marks" does not exist (ActiveRecord::StatementInvalid)
LINE 5:                WHERE a.attrelid = '"read_marks"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"read_marks"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
```

## Solution:

Verify that a model's database table exists before creating the model's dashboard.

### CODE REVIEW

**Comment by ACPK** [comment]
@graysonwright Awesome, thanks!

**Comment by JoelQ** [comment]
Should we output some kind of warning? ActiveRecord models should always be backed by a database table.

**Comment by graysonwright** [comment]
@JoelQ yeah, you're right. This might affect people who aren't up-to-date with their migrations, so we shouldn't be completely silent about it.

File: spec/generators/install_generator_spec.rb [hunk 1]
```diff
@@ -52,6 +53,20 @@
...
+      begin
+        class ModelWithoutDBTable < ActiveRecord::Base; end
+        stub_generator_dependencies
+        manifest = file("app/dashboards/dashboard_manifest.rb")
+
+        run_generator
+
+        expect(manifest).not_to contain("model_without_db_table")
+      ensure
+        remove_constants :ModelWithoutDBTable
```
Comment (JoelQ) [inline spec/generators/install_generator_spec.rb]: Does this need to be wrapped in `begin` /  `ensure` ?

**Comment by JoelQ** [comment]
One comment, otherwise LGTM :rocket:

File: spec/generators/install_generator_spec.rb (hunk 1 above)
Comment (graysonwright) [inline spec/generators/install_generator_spec.rb]: @JoelQ I want to make sure that we always clean up our constants, even if the test fails. It probably wouldn't affect much in this case, because we're not using `ModelWithoutDBTable` anywhere else. But in the past I've gotten some failures that were hard to track down because we weren't correctly cleaning up like this.

Also, in case you were asking about the ruby syntax side of things, yeah - you can't just use `ensure` or `rescue` inside a normal Ruby block. I believe those only work in methods.

Comment (JoelQ) [inline spec/generators/install_generator_spec.rb]: :+1:
