### PR TITLE
Let users undo the `administrate:views` generator

### LINKED ISSUE #310: destroy administrate:views not working
it seems that `generate` and `destroy` do the same thing:
```
masciugo@macbookpro ~/dev/ffm $ rails generate administrate:views Course
      create  app/views/admin/courses/index.html.erb
      create  app/views/admin/courses/_collection.html.erb
      create  app/views/admin/courses/show.html.erb
      create  app/views/admin/courses/new.html.erb
      create  app/views/admin/courses/_form.html.erb
      create  app/views/admin/courses/edit.html.erb
   identical  app/views/admin/courses/_form.html.erb
masciugo@macbookpro ~/dev/ffm $ rails destroy administrate:views Course
   identical  app/views/admin/courses/index.html.erb
   identical  app/views/admin/courses/_collection.html.erb
   identical  app/views/admin/courses/show.html.erb
   identical  app/views/admin/courses/new.html.erb
   identical  app/views/admin/courses/_form.html.erb
   identical  app/views/admin/courses/edit.html.erb
   identical  app/views/admin/courses/_form.html.erb
```

### PR DESCRIPTION
**Pull request by graysonwright**
Fixes #310

## Problem:

Rails provides a way to undo the effects of generators,
by running the command `rails destroy GENERATOR_NAME`.

With the way that we had set up our hierarchy of generators,
Rails did not know how to undo the effects of sub-generators.

For example, with the `administrate:views` generator,
we were calling `Rails::Generators.invoke("administrate:views:index")`.

Whether the generator was run with the `generate` or `destroy` command
did not make a difference -
the index generator would always be invoked
as if it were run with `generate`.

## Solution:

Rails generators use the `@behavior` instance variable to keep track of
how the generator was run.
This variable can be either `:invoke` or `:revoke`.

Pass this variable as an option to the sub-generators
to ensure they have the same behavior as the parent.

## Minor changes:

Extract `Administrate::GeneratorHelpers` to store common
generator-related methods.

### CODE REVIEW

File: lib/administrate/generator_helpers.rb [hunk 1]
```diff
@@ -0,0 +1,7 @@
+module Administrate
+  module GeneratorHelpers
+    def call_generator(generator, *args)
+      Rails::Generators.invoke(generator, args, behavior: behavior)
```
Comment (gylaz) [inline lib/administrate/generator_helpers.rb]: What do you think about passing `behavior` to `call_generator`? Otherwise, it seems like a mystery guest.

File: lib/administrate/view_generator.rb [hunk 2]
```diff
@@ -1,7 +1,9 @@
 require "rails/generators/base"
+require "administrate/generator_helpers"
 
 module Administrate
   class ViewGenerator < Rails::Generators::Base
+    include Administrate::GeneratorHelpers
```
Comment (gylaz) [inline lib/administrate/view_generator.rb]: Newline after this (before `private`)?

File: spec/generators/views_generator_spec.rb [hunk 3]
```diff
@@ -1,4 +1,4 @@
-require "spec_helper"
+require "rails_helper"
```
Comment (gylaz) [inline spec/generators/views_generator_spec.rb]: What is the reason this change is necessary?

**Comment by gylaz** [comment]
Left a few suggestions/questions. Looking good!

File: spec/generators/views_generator_spec.rb (hunk 3 above)
Comment (graysonwright) [inline spec/generators/views_generator_spec.rb]: When I ran this spec in isolation, it complained about not being able to find a module that Rails provides. I think we missed it before because we were always running this spec alongside others.

File: lib/administrate/view_generator.rb (hunk 2 above)
Comment (graysonwright) [inline lib/administrate/view_generator.rb]: done.

File: lib/administrate/generator_helpers.rb (hunk 1 above)
Comment (graysonwright) [inline lib/administrate/generator_helpers.rb]: normally I'd agree, but that would defeat the purpose of extracting this method. I wanted to automatically include the parent's behavior, instead of passing it in explicitly.
