### PR TITLE
Don't generate dashboards for non-constant models

### LINKED ISSUE #145: issues with `rake routes`
Half the time when I run my `rake routes` command I get the following error:

RailsApp/config/routes.rb:26:in `block (2 levels) in <top (required)>': uninitialized constant DashboardManifest (NameError)

Other times my routes print correctly to the console, but there's no listing for my admin namespaced routes.

I've seen the `uninitialized constant DashboardManifest (NameError)` error pop up randomly when using generators as well, but the error doesn't seem to appear consistently.

### PR DESCRIPTION
**Pull request by graysonwright**
Fixes #145 and #219

## Problem:

When the same `has_and_belongs_to_many` relationship is defined twice,
Rails generates an unnamed subclass of `ActiveRecord::Base`.
This is probably a bug in Rails.

The unnamed subclass shows up like this:

```ruby
> ActiveRecord::Base.descendants.last
 #<Class:0x007fddea1bdf08> (call '#<Class:0x007fddea1bdf08>.connection' to establish a connection)
```

When the install generator tries to populate the `DashboardManifest`
with all of the `ActiveRecord` models,
it trips up on unnamed models,
and generates a manifest with invalid syntax.

This results in a `NameError` for the user when they run the
`administrate:install` generator:

```
/gems/administrate-0.1.0/lib/generators/administrate/dashboard/dashboard_generator.rb:87:
in `const_get': wrong constant name #<class:0x007fcf52bfe248> (NameError)
```

This error most often pops up in applications
that are using the `spring` gem.

## Solution:

- Add a test case that reproduces the error
  by defining duplicate `has_many` associations.
- In the install generator, ignore any models that are not constants.
  We determine constants by checking that the model's `#name`
  matches its `#to_s`.
- Print a warning for the ignored models.

### CODE REVIEW

File: lib/generators/administrate/install/install_generator.rb [hunk 1]
```diff
@@ -40,6 +40,11 @@ def warn_about_invalid_models
           puts "WARNING: Unable to generate a dashboard for #{invalid_model}."
           puts "         It is not connected to a database table."
         end
+
+        unnamed_constants.each do |invalid_model|
+          puts "WARNING: Unable to generate a dashboard for #{invalid_model}."
+          puts "         It is not a valid Ruby constant."
```
Comment (jakecraige) [inline lib/generators/administrate/install/install_generator.rb]: Is there something that could be linked to the user to help them debug/fix this?

Comment (graysonwright) [inline lib/generators/administrate/install/install_generator.rb]: @jakecraige I... don't know.

I'm about 85% sure this is a bug in Rails, and I'm going to open a PR there to try to fix it. On the user's end, they're probably not aware they even have a non-constant class in their application, so it'll be strange for them to see a warning.

I'm considering removing this warning altogether, or changing it to something less scary-sounding, like:

```
NOTICE: Skipping dynamically generated model `#<Class:asdfasdf>`.
```

Thoughts?

**Comment by graysonwright** [comment]
Ping @sgrif - figured out the issue where ActiveRecord is creating unnamed classes. Looks like it's a bug in ActiveRecord - is that right?

I have the bandwidth to open up a PR for it, if you'd like.

**Comment by graysonwright** [comment]
Talked to @sgrif - since calling `has_and_belongs_to_many` multiple times for the same relationship isn't a supported use case in Rails, the bug actually lives in Spring. For some reason, it's reloading the relationship when it shouldn't be.

**Comment by sgrif** [comment]
> For some reason, it's reloading the relationship when it shouldn't be.

More likely it's retaining the constant that should be getting released as part of the general constant reloading process.

**Comment by graysonwright** [comment]
yep, good catch. Thanks!

File: lib/generators/administrate/install/install_generator.rb (hunk 1 above)
Comment (sgrif) [inline lib/generators/administrate/install/install_generator.rb]: I spent a bit thinking about this. Does this even need to be a warning? I feel like we can pretty certainly say that if a class isn't assigned to a constant, you can ignore it. (Also you should look at the implementation of `descendants` if you haven't in the past, because it's hilarious)

**Comment by Rodrigora** [comment]
Cool @graysonwright. :100: 

Just letting you know that I do not have duplicated `HABTM` relationships. These are my models:

```ruby
class Feature < ActiveRecord::Base
  has_and_belongs_to_many :units
end

class Unit < ActiveRecord::Base
  has_and_belongs_to_many :features
end
```

**Comment by graysonwright** [comment]
@Rodrigora yep, I think there may be a bug in [spring](https://github.com/rails/spring) that is causing the equivalent effect of a duplicated HABTM relationship.

Are you using spring in your app?

**Comment by Rodrigora** [comment]
Yes @graysonwright, I'm using it. 

You're right, certainly it is a Spring bug. Thanks!
